### ISSUE TITLE
support for tweed deluxe

### ISSUE THREAD

**Issue by jgomer2001** [jatalahd/tsc#10]
Hi,

I am a happy user of TSC - very handy tool.

I was wondering if you could add the 5E3 (tweed deluxe) circuit, or let me know if I can get similar results with one of the existing circuits (princeton?) - what values could I use ?

Thanks for reading.

**Comment by jgomer2001** [comment]
I was checking schematics - I found the 5E3 preamp section is different compared to that of 5E2. I'm not knowledgeable about this stuff unfortunately

I'd appreciate any comment @jatalahd @TheseGoTo11

**Comment by jatalahd** [comment]
Hi,

Someone requested the 5E3 tone stack a few years ago and at that time I refused to add that because at least from theoretical perspective there is coupling between the bright and normal volume controls. The effect is that tone for example the "normal" signal path is changed if the volume pot of "bright" signal path is turned. The other way around the coupling is not that obvious tho. If you look at for example the 6G3 schematic, they have improved the design and removed the coupling.

So for this specific amp I would need to make separate tone stack models for "normal" and "bright" signal paths. Is this what you need or will only one of them do? You will not get similar results from any of the existing tone stack models, although the 5f2a is similar but "rotated".

**Comment by jgomer2001** [comment]
Right. Yesterday I was reading about that fact (tone affected by the other, unplugged channel's volume).

I'd appreciate if you could add the tone stack for 5E3 "normal" whenever you have the chance.

Thanks for reading.

**Comment by jatalahd** [comment]
Added the model for deluxe 5E3, it turned out to be weirder than I expected. In my analysis there is a loading effect also from the "bright" channel tube output impedance, which is approx 20k for 12AY7. Not sure if this is the case in real life, but it appears that when "bright" channel volume is at max, it drops the "normal" channel volume quite considerably, due to the loading effect of the tube output. If this does not occur in reality, then that phenomena can be eliminated by editing the value of RINB to 1M or more. Also in general it seems that the "normal" channel is quite "bass heavy".

The stack model is live at my website so you can test it out.

**Comment by jgomer2001** [comment]
Thanks.

I don't have a tweed but from what I know is that tweed deluxe:

a) features fat, loose low mids
b) when the unused volume knob is turned counter-clockwise, the preamp gain increases (dirtier sound), and viceversa
c) at low volume levels, the tone at noon offers a rather flat response
d) at low volume levels, the tone beyond noon increases upper mids (around 2KHz I suppose)
e) at higher volume leves, the effect of tone control is similar but way subtler

From what I can see, TSC confirms statements _a_, _b_, and _c_. However _d_ and _e_ don't seem to be there. There might be something off with that tone control, for instance note how highs are always reduced when using a value beyond 8...

Maybe you would like to double check when you have some spare time. Perphaps this [article](https://robrobinette.com/How_The_5E3_Deluxe_Works.htm) is helpful? it's beyond by paygrade

**Comment by jatalahd** [comment]
I know many will think that there is something off with the model, but in my opinion the true problem is in the tone stack design itself. The "value beyond 8" effect is simple to see directly from the schematic. Assume "bright" channel volume down to 0, "normal" volume at 5, turn tone pot to far "left" and then far "right". In far left you have 5000pF cap to ground and far right you have 500pF cap (parallel to 1M resistor ) to ground, and 5000/500 = 10. The -3dB cutoff frequency is about 200 Hz at left and 2000 Hz at right and 2000/200 = 10. So intuitively that is how the circuit works and the TSC shows that. When the "normal" volume is turned  towards max, the R in 1/RC corner frequency formula gets smaller and cutoff frequencies move higher, but still with 10 to 1 ratio. When the tone pot is in the middle, it separates both caps with 500k resistance, so there is practically no filtering to ground from either cap. That is why the response is flat.

As for e) at higher volumes one can claim that the tone control becomes more subtle as the cutoff frequency moves further away from the main frequency range of the guitar so that the tone is perceived to change less.

As for d) that is quite what happens, frequencies between ~300 Hz to 2000 Hz are boosted, so that range includes mids + higher mids. Maybe here the perceived change by ear focuses more on the frequencies near 1000 Hz.

I claim that the model I did shows how the circuit works, but yes I admit I did not have time to verify against SPICE simulations. As you can see I have not made many contributions to this repository in the last two years, because I have been busy at work, therefore unfortunately I cannot put any more time to this. If someone wants to prove me wrong (or right), all they need to do is to simulate the circuit in SPICE for some fixed pot values and compare to the graph shown in the TSC web page. If there are differences, a new issue can be opened and I will try to fix it then.
