### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by tubegeek** [jatalahd/tsc#3]
On my screen (in chrome) the capacitance and resistance values are in units of picofarads and ohms. For resistances this usually results in the value being only shown partially (the value box is too narrow to show the whole value.) This sometimes happens with capacitance as well.

Is it possible to widen the values panel a bit? Or make it re-sizeable for times when you want to see the whole value?

I'd be remiss if I didn't temper my suggestion with a LOUD THANK YOU for this great project, I love using it and it just keeps getting better and better.

**Comment by jatalahd** [comment]
The layout was originally designed for minimum screen resolution width of 1280 pixels. If you have a smaller resolution than this, or you have some additional zoom setup in your browser, then the layout will be compressed and basically broken. My 12 year old laptop has the width resolution set as 1280 px and using Linux OS, there is plenty of space in the values panel to show the numbers (tested using firefox and chromium). I also tested with Chrome and MS Edge browsers on a Windows laptop and I don't see a problem there. 

Could you please provide some more info on your screen resolution and perhaps a screencapture to visualize the problem?

I am planning to "fix" this by setting a fixed width of 1250 to the outmost table element, currently there is no value set for that. This will make it so that the inner parts of the table will stay at the fixed width they have now, but will cause a scrolling bar to appear at the bottom of the page when the 1250 pixels exceeds the resolution limits of the device used. Then you would have to scroll the whole page left/right on smaller screens or when zoom is enabled in browser. Would this be acceptable solution for you (assuming that it actually fixes the problem of the values panel being too narrow) ?

**Comment by tubegeek** [comment]
@jatalahd - thanks for your explanation and response. Your responsiveness on this project is and has been fantastic, I must thank you again.

Your reply gave me an idea which worked just fine: I full-screened my browser (chrome) and sure enough the display was sized quite well and the issue I reported wasn't an issue any more. My display is 1280 x 800, FYI, it's an old laptop also, a Mac Pro.

I think a perfectly reasonable workaround for my situation would just be to use TSC For The Web in fullscreen mode, so no changes need to be made for that to work in my case. I don't know what others are experiencing or how much you are concerned with, say, mobile phone access, so I leave the situation in your more-than-capable hands!

I'll attach some screenshots to address your question about what it looks like.
![fullscreen](https://user-images.githubusercontent.com/73593549/97780649-4a27de00-1b5c-11eb-86c8-cbd75566f96e.jpg)
![smaller](https://user-images.githubusercontent.com/73593549/97780650-4ac07480-1b5c-11eb-9fc6-7ebbd75218d9.jpg)



FYI, I'm part of a few of gear-geek communities, e.g., TDPRI, diystompboxes, there are others, and we all love your implementation - AND EXTENSION! - of the TSC. The fan club is huge and grateful. Thanks!

Best,

Jeremy (tubegeek)

**Comment by jatalahd** [comment]
Ok, thank you for clarifying the issue and for the positive feedback. I will close this issue without any fixes. I guess it can be reopened again in the future if necessary.
